apiVersion: v1
kind: Namespace
metadata:
  name: observe
  annotations:
    observeinc.com/cluster-name: dev-us-east-1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: winlogs
spec:
  template:
    spec:
      containers:
        - name: fluentd
          resources:
            limits:
              cpu: 500m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 2048Mi
