apiVersion: v1
kind: Namespace
metadata:
  name: observe
  annotations:
    observeinc.com/cluster-name: dev-us-east-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  template:
    spec:
      containers:
        - name: kube-state-events
          resources:
            limits:
              cpu: 400m
              memory: 2Gi
            requests:
              cpu: 400m
              memory: 2Gi
